#ifndef GUI_CONSTANCY_H
#define GUI_CONSTANCY_H

#define TIMEOUT1_KEY2 15    // 15 * 50ms = 750ms
#define TIMEOUT2_KEY2 60    // 60 * 50ms = 3s

enum INPUT_MODE{INPUT_MODE_BUTTON, INPUT_MODE_ENCODER};
enum KEY_CODES{KEY0_DOWN, KEY0_UP, KEY1_DOWN, KEY1_UP, KEY2_DOWN, KEY2_UP, KEY2_TIMEOUT1, KEY2_TIMEOUT2, NO_KEY};
enum GUI_MODE{GUI_INFO_MODE, GUI_MENU_MODE, GUI_FILE_BROWSER};

#endif // GUI_CONSTANCY_H
