#ifndef GUI_CONSTANCY_H
#define GUI_CONSTANCY_H

enum KEY_CODES{KEY0_DOWN, KEY0_UP, KEY1_DOWN, KEY1_UP, KEY2_DOWN, KEY2_UP, NO_KEY};

enum GUI_MODE{GUI_INFO_MODE, GUI_MENU_MODE};

#endif // GUI_CONSTANCY_H
